FROM node:18.8.0

LABEL org.opencontainers.image.authors="marko.uksanovic1@gmail.com"

ENV DB_CONNECTION, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD

WORKDIR /app

RUN mkdir /blender && \
    curl -o \
        /tmp/blender.tar.xz -L \
        "https://mirror.clarkson.edu/blender/release/Blender3.3/blender-3.3.1-linux-x64.tar.xz" && \
    apt update && \
    apt upgrade -y && \
    apt install --no-install-recommends -y \
        ocl-icd-libopencl1 \
        xz-utils \
        libxi6 \
        libxxf86vm-dev \
        libxxf86vm-dev \
        libxcursor-dev \
        libxi-dev \
        libxrandr-dev \
        libxinerama-dev \
        libegl-dev && \
    apt install --no-install-recommends -y \
        libwayland-dev \
        wayland-protocols \
        libxkbcommon-dev \
        libdbus-1-dev \
        linux-libc-dev && \
    ln -s libOpenCL.so.1 /usr/lib/x86_64-linux-gnu/libOpenCL.so && \
    tar xf \ 
        /tmp/blender.tar.xz -C \
        /blender/ --strip-components=1 && \
    ln -s \
        /blender/blender \
        /usr/bin/blender && \
    rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/*

RUN apt install ffmpeg libavdevice58=7:4.1.6-1~deb10u1

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "run", "worker"]