FROM node:18.8.0

LABEL org.opencontainers.image.authors="marko.uksanovic1@gmail.com"

ENV DB_CONNECTION, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD

WORKDIR /app

RUN apt-get update -y && \
    apt-get install python3.9 -y && \
    apt-get install python3-pip -y && \
    python3.9 -m pip install zstandard 

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]
