version: "3"

services:
  assign2:
    image: "ghcr.io/markopteryx/cab432-n8039062-worker:main"
    container_name: assign2
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/app/.env