version: '3'

services:
  backend:
    image: ghcr.io/markopteryx/cab432-n8039062-backend:main
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - /home/ubuntu/app/.env

  frontend:
    image: ghcr.io/markopteryx/cab432-n8039062-frontend:main
    container_name: frontend
    restart: always
    ports:
      - 80:3000
    stdin_open: true
    env_file:
      - /home/ubuntu/app/.env